### ISSUE TITLE
Launches the login Widget but I get a white screen on second login

### ISSUE THREAD

**Issue by scottdickerson** [ibm-cloud-security/appid-clientsdk-swift#96]
I have an issue where I'm trying to use app id with facebook and google from the login widget.
I have a button that launches the login widget with this code: 
AppID.sharedInstance.loginWidget?.launch(delegate: self)
It seems to work fine on the first test.

However on the second time I start the app, if I click the button that launches the loginWidget, instead of allowing me to choose which provider to use to authenticate with, the loginWidget flashes the Google/Facebook choice page for a split second, then takes me to a white screen.

I'm assuming the backend page is determining that I'm already authenticated and trying to take me somewhere else, but if this is the case, why does the loginWidget show at all?  I thought the loginWidget.launch wasn't supposed to launch if I'm already authenticated.  Is there an API that I can call to determine that I'm already authenticated with app ID so I can skip my login page?

**Comment by cirilla** [comment]
Hi, I tried to reproduce your issue but I don't see it happen, can you please make sure you follow the documentation and perform login exactly like it is done at the sample project.
if you still have this issue please can you please provide us your project?

**Comment by swiftfoot** [comment]
Are there any logs available on the server side of the app id config that I could provide? It seems as if the server side is redirecting me to a blank page.

On May 19, 2017, at 4:14 AM, Cirill <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I tried to reproduce your issue but I don't see it happen, can you please make sure you follow the documentation and perform login exactly like it is done at the sample project.
if you still have this issue please can you please provide us your project?
