### ISSUE TITLE
Can we get a carthage version of this framework?

### ISSUE THREAD

**Issue by scottdickerson** [ibm-cloud-security/appid-clientsdk-swift#97]
I don't like to build my framework source files everytime we build, it slows down our build process and flags warnings in the underlying libraries source code.  It also skews our code coverage numbers incorrect in our xcode build reports.

Can we get a version of this library published to Carthage?  
https://github.com/carthage/carthage

**Comment by tkhm** [comment]
I agree with @swiftfoot 
Is there any plan?

**Comment by motyd** [comment]
There are no plans for it in the near future.
