### ISSUE TITLE
FYI: Need of "import BMSCore" in chapter "Using Login Widget"

### ISSUE THREAD

**Issue by thomassuedbroecker** [ibm-cloud-security/appid-clientsdk-swift#99]
I notice you need also import BMSCore, because ob the response definition in this call.

```
public func onAuthorizationSuccess(accessToken: AccessToken, identityToken: IdentityToken, response:Response?) {
            //User authenticated
        }
```
After I inserted import BMSCore and import BluemixAppID, the compiler error disappeared. 
That means you have to add  import BMSCore and import BluemixAppID in your file, where you will use the class.

**Comment by cirilla** [comment]
We are using BMSCore internally, it is mandatory to import it in your class
